// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwZ9BKtRtgSTIuTzj5sZAb_rr9huo1tlA',
    appId: '1:650378430699:web:5ee795b8b019cf94b156ae',
    messagingSenderId: '650378430699',
    projectId: 'tamarattendence-e95d8',
    authDomain: 'tamarattendence-e95d8.firebaseapp.com',
    storageBucket: 'tamarattendence-e95d8.firebasestorage.app',
    measurementId: 'G-K06PCEDLY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5f-9fq4tqfPKjrS8r8qPS4Cxb-mh60Lw',
    appId: '1:650378430699:android:50cc9a0f4eebefc7b156ae',
    messagingSenderId: '650378430699',
    projectId: 'tamarattendence-e95d8',
    storageBucket: 'tamarattendence-e95d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEZ-RVXXniBePSvd6emxV4jLWFvljzl5Q',
    appId: '1:650378430699:ios:f49694e8655aea34b156ae',
    messagingSenderId: '650378430699',
    projectId: 'tamarattendence-e95d8',
    storageBucket: 'tamarattendence-e95d8.firebasestorage.app',
    iosBundleId: 'com.example.tamarAttendence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEZ-RVXXniBePSvd6emxV4jLWFvljzl5Q',
    appId: '1:650378430699:ios:f49694e8655aea34b156ae',
    messagingSenderId: '650378430699',
    projectId: 'tamarattendence-e95d8',
    storageBucket: 'tamarattendence-e95d8.firebasestorage.app',
    iosBundleId: 'com.example.tamarAttendence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwZ9BKtRtgSTIuTzj5sZAb_rr9huo1tlA',
    appId: '1:650378430699:web:d1d6fb70b9ce16fdb156ae',
    messagingSenderId: '650378430699',
    projectId: 'tamarattendence-e95d8',
    authDomain: 'tamarattendence-e95d8.firebaseapp.com',
    storageBucket: 'tamarattendence-e95d8.firebasestorage.app',
    measurementId: 'G-MBE5271EHP',
  );

}